### ISSUE TITLE
Problem: absolute path to `basename` used in backup script

### ISSUE THREAD

**Issue by lenards** [cyverse/atmosphere-ansible#113]
The script that is deployed and available for backup/restore is using [`/bin/basename`](https://github.com/cyverse/atmosphere-ansible/blob/master/ansible/roles/atmo-backup/files/cyverse_backup.sh#L263) instead of locating the `basename` executable. This means that a change for `basename` to `/usr/bin/basename` breaks the script.

For an Ubuntu 16.04 instance ... 
```
lenards@vm000-00:~$ ls -lha /bin/ | grep basename
lenards@vm000-100:~$ ls -lha /usr/bin/ | grep basename
-rwxr-xr-x  1 root   root     31K Mar  2  2017 basename
lenards@vm000-100:~$ ls -lha /sbin/ | grep basename
```

One approach might be to capture the location in a variable, `BASENAME=$(which basename)`, and then use that in determined the remote location.

**Comment by calvinmclean** [comment]
Commit 50d895d8f3cc107d3b73a527687e2585fc55b342 has a fix for this issue. The commit message says it is a _temporary_ fix so this is a comment just for documentation 👍
