### ISSUE TITLE
python2 doesn't exist on instance, required by ansible

### ISSUE THREAD

**Issue by cdosborn** [cyverse/atmosphere-ansible#119]
The following section detects python 3 installs python 2:
https://github.com/cyverse/attmosphere-ansible/blob/0a352c14769e382dd8eb7928bb3294fdf97186a1/ansible/roles/atmo-ssh-setup/tasks/main.yml#L57-L68

However it doesn't detect python 3 correctly. Testing whether a user has ssh is not sufficient. @c-mart found that an Ubuntu 16.04 instance had ssh access as root, which resulted in no python2 install.

A simple fix (and what seems more correct) is to ensure that python 2 independent even of the distro.

**Comment by c-mart** [comment]
How about we just run the `raw` command on every instance?

**Comment by c-mart** [comment]
While looking at ceph-ansible this morning I noticed [how they do this](https://github.com/ceph/ceph-ansible/blob/master/site.yml.sample#L23-L41). If ansible can't see `/usr/bin/python` via `stat` module then `raw` module is run repeatedly with commands for both Debian-based and RHEL-based systems.

**Comment by cdosborn** [comment]
Cool find. Would be a useful role, seems like most projects would need this..
