### ISSUE TITLE
Switch iRODS package downloads to HTTPS

### ISSUE THREAD

**Issue by c-mart** [cyverse/atmosphere-ansible#160]
We no longer need to use iRODS' insecure FTP server: <https://files.renci.org/pub/irods/>

Roles that should be updated:
- atmo-kanki-irodsclient
- atmo-irods

**Comment by calvinmclean** [comment]
@c-mart I'll do this if you're not already working on it

**Comment by calvinmclean** [comment]
It turns out that `atmo-irods` is never used in our playbooks. Instead, `irods-icommands` is used.
Can I remove the `atmo-irods` role in this PR or should I save that for a different PR?

**Comment by c-mart** [comment]
@calvinmclean I would separate them out.
