### ISSUE TITLE
Remove duplicate `Port` entry for `sshd_config`

### ISSUE THREAD

**Issue by nfaction** [cyverse/atmosphere-ansible#29]
Ubuntu 14.04.2 XFCE Base instance contains both:

```
Port 1657
Port 22
```

Should add either lineinfile to remove all entries and add just the desired port for SSH using regex to remove, then add again.  Only then SSH can be restarted

**Comment by calvinmclean** [comment]
@c-mart @steve-gregory 
I believe we can close this issue after PR #62

**Comment by calvinmclean** [comment]
Actually, I just launched an instance and both port entries are still there...

**Comment by lenards** [comment]
Fixed by #66.
