### ISSUE TITLE
Delete compressed files on atmosphere instances to make space

### ISSUE THREAD

**Issue by amercer1** [cyverse/atmosphere-ansible#45]
Atmosphere-ansible: After initial SSH login, check the total disk usage. if >90% include+run additional playbooks/roles
 |---> Examples include: 
     rm /opt/_.tar
     rm /opt/_.tar.gz
     ... more to come

**Comment by amercer1** [comment]
JIRA ISSUE `ATMO-1464`

**Comment by calvinmclean** [comment]
This can be closed. See here: https://github.com/cyverse/atmosphere-ansible/pull/46
